// Fake units data for testing and demonstration purposes

export const fakeUnits = [
  {
    id: "unit-1",
    number: "101",
    name: "جناح ديلوكس",
    status: "occupied" as const,
    guest: "محمد أحمد العلي",
    checkIn: "2024-01-15",
    checkOut: "2024-01-20",
    balance: 1500,
    type: "suite" as const,
    floor: "1",
    pricePerNight: 500,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-2",
    number: "102",
    name: "غرفة عادية",
    status: "vacant" as const,
    type: "room" as const,
    floor: "1",
    pricePerNight: 300,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-3",
    number: "103",
    name: "جناح رئاسي",
    status: "departure-today" as const,
    guest: "سارة محمد الخالد",
    checkIn: "2024-01-10",
    checkOut: "2024-01-18",
    balance: 0,
    type: "suite" as const,
    floor: "1",
    pricePerNight: 800,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-4",
    number: "104",
    name: "غرفة مزدوجة",
    status: "arrival-today" as const,
    guest: "أحمد خالد السعيد",
    checkIn: "2024-01-18",
    checkOut: "2024-01-25",
    balance: 3200,
    type: "room" as const,
    floor: "1",
    pricePerNight: 400,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-5",
    number: "105",
    name: "استوديو",
    status: "out-of-service" as const,
    type: "studio" as const,
    floor: "1",
    pricePerNight: 350,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-6",
    number: "201",
    name: "جناح عائلي",
    status: "occupied" as const,
    guest: "فاطمة علي الحسن",
    checkIn: "2024-01-12",
    checkOut: "2024-01-22",
    balance: 800,
    type: "suite" as const,
    floor: "2",
    pricePerNight: 600,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-7",
    number: "202",
    name: "غرفة فردية",
    status: "vacant" as const,
    type: "room" as const,
    floor: "2",
    pricePerNight: 250,
    city: "الرياض",
    propertyId: "1",
  },
  {
    id: "unit-8",
    number: "203",
    name: "جناح تنفيذي",
    status: "occupied" as const,
    guest: "عمر حسين الرشيد",
    checkIn: "2024-01-16",
    checkOut: "2024-01-19",
    balance: 0,
    type: "suite" as const,
    floor: "2",
    pricePerNight: 700,
    city: "الرياض",
    propertyId: "1",
  }
];

export type FakeUnit = typeof fakeUnits[number];